# Generated by Django 3.0.5 on 2020-04-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=16, unique=True)),
                ('u_email', models.CharField(max_length=24)),
                ('u_password', models.CharField(max_length=16)),
                ('u_register_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
