# Generated by Django 3.0.5 on 2020-04-13 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_title', models.CharField(max_length=128)),
                ('a_text', models.TextField(null=True)),
                ('a_create_time', models.DateTimeField(auto_now_add=True)),
                ('a_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User')),
                ('a_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.Subject')),
            ],
        ),
    ]
