# Generated by Django 3.0.5 on 2020-04-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=16, unique=True)),
                ('admin_email', models.CharField(max_length=24)),
                ('admin_password', models.CharField(max_length=16)),
            ],
        ),
    ]
